name: counter_bloc
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc:
  flutter_bloc:
  provider: ^4.0.5
  flutter:
    sdk: flutter
  remote_state:
    path: ../../packages/remote_state
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
