name: counter_state_notifier
version: 1.0.0+1
homepage: https://github.com/chimon2000/remote_state
author: Ryan Edge <ryan.c.edge@outlook.com>
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  remote_state:
    path: ../../packages/remote_state
  flutter_state_notifier: ^0.7.0
  provider: ^5.0.0-nullsafety.5
  state_notifier: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
